package stuff;

import java.util.HashMap;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

@ManagedBean
@ApplicationScoped
public class Master
{
	private Map <String, String> users;

	@PostConstruct
	public void initialise()
	{
		users = new HashMap<String, String>();
		users.put("NermaN", "");
		users.put("Crystal the Glaceon", "");
		users.put("RustInPeace", "");
		users.put("Pyra", "");
		users.put("iAqua", "");
		users.put("JosephNeale", "");
		users.put("CrispyYoshi", "");
		users.put("KumpelKuerbis", "");
		users.put("angelus kun", "");
		users.put("OrGoN3", "");
		users.put("Bigkuhuna24", "");
		users.put("AecdArmy", "");
		users.put("sks316", "");
		users.put("xJoelituh", "");
		users.put("Hayleia", "");
		users.put("Kyousak", "");
		users.put("XXXTORTELLINI", "");
		users.put("dsaucedo98", "");
		users.put("j103", "");
		users.put("RevX1", "");
		users.put("GerbilSoft", "");
		users.put("AwakeArk", "");
		users.put("adrifcastr", "");
		users.put("daJoschi", "");
		users.put("Saternoir", "");
		users.put("R3V3RS3", "");
		users.put("jaykureno", "");
		users.put("arc13", "");
		users.put("Johnal Khow", "");
		users.put("Majickhat55", "");
		users.put("dajoschi", "");
		users.put("nbaptistes71", "");
		users.put("chaoskagami", "");
		users.put("Yangarang", "");
		users.put("RosaliinaDaHacker64", "");
		users.put("CyberTails", "");
		users.put("cheuble", "");
		users.put("Elveman", "");
		users.put("riyaz", "");
		users.put("jackb994", "");
		users.put("Elysium420", "");
		users.put("Jhynjhiruu", "");
		users.put("Disco Inferno", "");
		users.put("ashudow", "");
		users.put("bomigoton", "");
		users.put("Kourin", "");
		users.put("UsujioTarako", "");
		users.put("W4T4R1", "");
		users.put("hyprskllz", "");
		users.put("Arubaro", "");
		users.put("froggydarren", "");
		users.put("Ev1l0rd", "");
		users.put("Arkadiy", "");
		users.put("Kartik", "");
		users.put("opa334", "");
		users.put("darkalex004", "");
		users.put("Margen67", "");
		users.put("DarkGabbz", "");
		users.put("sifiro", "");
		users.put("Voxel", "");
		users.put("Metalik", "");
		users.put("HenryLeonheart", "");
		users.put("retrofan_k", "");
		users.put("Noriko", "");
		users.put("greenDarkness555", "");
		users.put("THEELEMENTKH", "");
		users.put("Lia", "");
		users.put("Gaboros", "");
		users.put("GravitySuitCollector", "");
		users.put("maalni", "");
		users.put("TVL", "");
		users.put("osm70", "");
		users.put("Sobliv", "");
		users.put("V0ltron", "");
		users.put("alsacchi", "");
		users.put("Xe-rom", "");
		users.put("CodyMKW", "");
		users.put("GSFanatic", "");
		users.put("ixoos", "");
		users.put("DinohScene", "");
		users.put("Kyubnyan", "");
		users.put("Cammykins", "");
		users.put("Romain80200", "");
		users.put("kprovost7314", "");
		users.put("kenoon", "");
		users.put("Bullseye", "");
		users.put("Procyon", "");
		users.put("THYPLEX", "");
		users.put("aos10", "");
		users.put("Carnelian", "");
		users.put("Naked_Snake", "");
		users.put("yacepi15", "");
		users.put("SigHaxMasterRace", "");
		users.put("jaysea", "");
		users.put("Tesslaa", "");
		users.put("dubbz82", "");
		users.put("Magical Sheep", "");
		users.put("Niels Van Son", "");
		users.put("PrometheusG.", "");
		users.put("nitro", "");
		users.put("Salamencizer", "");
		users.put("Gnarmagon", "");
		users.put("Powerful", "");
		users.put("Epicdaftman", "");
		users.put("sora10pls", "");
		users.put("ThommyTheBoy", "");
		users.put("Supster131", "");
		users.put("TheDarkGreninja", "");
		users.put("jsa", "");
		users.put("Xyphoseos", "");
		users.put("jacklack3", "");
		users.put("ixoos", "");
		users.put("Dayfid", "");
		users.put("thisisallowed", "");
		users.put("BL4Z3D247", "");
		users.put("clownb", "");
		users.put("luigoalma", "");
		users.put("blujay", "");
		users.put("dorisnov", "");
		users.put("peteruk", "");
		users.put("Gray_Jack", "");
		users.put("Biff627", "");
		users.put("Gaikonaiko", "");
		users.put("Aletron9000", "");
		users.put("Holiday_Ougi", "");
		users.put("JorrickL", "");
		users.put("Stephano", "");
		users.put("thaikhoa", "");
		users.put("Evernew", "");
		users.put("Alex1234", "");
		users.put("Nevostrius", "");
		users.put("skullkeeper94", "");
		users.put("sniper_x002", "");
		users.put("Psi-hate", "");
		users.put("dradonhunter11", "");
		users.put("Txustra", "");
		users.put("Jackpot3000", "");
		users.put("Tenshi_Okami", "");
		users.put("8BitWonder", "");
		users.put("SomeGamer", "");
		users.put("Robbo_gbar", "");
		users.put("NicoAICP", "");
		users.put("LukeFZ", "");
		users.put("Crusard", "");
		users.put("gnmmarechal", "");
		users.put("Serial07", "");
		users.put("ImCarlosGG", "");
		users.put("TheKingy34", "");
		users.put("N7Kopper", "");
		users.put("jpxdude", "");
		users.put("trainboy2019", "");
		users.put("SirECK", "");
		users.put("ov3rkill", "");
		users.put("TyBlood13", "");
		users.put("noragrets", "");
		users.put("Damin72", "");
		users.put("Lukerz", "");
		users.put("STVS Studios", "");
		users.put("Attainable", "");
		users.put("pokeemerald", "");
		users.put("R9HAX", "");
		users.put("Sophie-bear", "");
		users.put("KevinX8", "");
		users.put("Reachdjz", "");
		users.put("zsinx6", "");
		users.put("OkazakiTheOtaku", "");
		users.put("Scarecrow B", "");
		users.put("soulkyo", "");
		users.put("anon3536", "");
		users.put("sniper_x002", "");
		users.put("ipodtouchdude", "");
		users.put("Dionicio3", "");
		users.put("sup3rgh0st", "");
		users.put("Kushan", "");
		users.put("Noroxus", "");
		users.put("trigao", "");
		users.put("Rick Astley", "");
		users.put("HamBone41801", "");
		users.put("nwhiteman42", "");
		users.put("jurassicplayer", "");
		users.put("Fra", "");
		users.put("usagirei", "");
		users.put("frogboy", "");
		users.put("autism4n", "");
		users.put("Oso", "");
		users.put("HugaTheFox", "");
		users.put("Sora Takihawa", "");
		users.put("PlatinumMaster", "");
		users.put("monkey69", "");
		users.put("SkyQueen", "");
		users.put("drenal", "");
		users.put("makzk", "");
		users.put("Grifnelle", "");
		users.put("Dvir", "");
		users.put("Mr.Faq2015", "");
		users.put("Diego788", "");
		users.put("GamingAori", "");
		users.put("pasoka", "");
		users.put("Skyshadow101", "");
		users.put("ProspitPrince", "");
		users.put("NicholasCullihal", "");
		users.put("Maciek", "");
		users.put("xXHomebrewHackerXx", "");
		users.put("C0mm4nd_", "");
		users.put("Rizzorules", "");
		users.put("Starboy", "");
		users.put("XxShalevElimelechxX", "");
		users.put("Dracari", "");
		users.put("Sandvich_Hero", "");
		users.put("my2k2zx2", "");
		users.put("b1g4s", "");
		users.put("duwen", "");
		users.put("Piluvr", "");
		users.put("souler92", "");
		users.put("3than_H", "");
		users.put("BBR", "");
		users.put("wg93589", "");
		users.put("El1lbl0w", "");
		users.put("lefthandsword", "");
		users.put("xppancho", "");
		users.put("JackAttackYT", "");
		users.put("JustaMew", "");
		users.put("KunoichiZ", "");
		users.put("erman1337", "");
		users.put("justaMew", "");
		users.put("wyoming", "");
		users.put("pandavova", "");
		users.put("LinkSoraZelda", "");
		users.put("Thunder Hawk", "");
		users.put("Hking0036", "");
		users.put("Aluminite", "");
		users.put("Gimzie", "");
		users.put("gamemasteru03", "");
		users.put("V0ltr0n", "");
		users.put("jaeman109", "");
		users.put("TheTheTony", "");
		users.put("Traiver", "");
		users.put("Disharmony16", "");
		users.put("iAqua", "");
		users.put("FrankenMan", "");
		users.put("Pheinte", "");
		users.put("xtheman", "");
		users.put("wolf_", "");
		users.put("gui710", "");
		users.put("Mr Skinner", "");
		users.put("johnbus", "");
		users.put("natanelho", "");
		users.put("gamer765", "");
		users.put("NightLunya", "");
		users.put("sweatbox", "");
		users.put("fr3quency", "");
		users.put("Petraplexity", "");
		users.put("ZERO2028", "");
		users.put("pokecraft98", "");
		users.put("Filo97", "");
		users.put("Dgabriel", "");
		users.put("JoshuaDoes", "");
		users.put("Xeon3D", "");
		users.put("TheCheeze", "");
		users.put("acelerador", "");
		users.put("Somovsky", "");
		users.put("ninja_035", "");
		users.put("Grenigga", "");
		users.put("Cesar9883", "");
		users.put("NekoMichi", "");
		users.put("Salvador Gremory", "");
		users.put("Ichiriki", "");
		users.put("Calsam12", "");
		users.put("Armandik", "");
		users.put("DubstepImpact", "");
		users.put("LiveLatios", "");
		users.put("Urbanshadow", "");
		users.put("somethingwet", "");
		users.put("KiraBlaize", "");
		users.put("TheCyberQuake", "");
		users.put("DespyCL", "");
		users.put("runetoonxx2", "");
		users.put("justneet", "");
		users.put("DualBladedKirito", "");
		users.put("DaftMink", "");
		users.put("BlueFox", "");
		users.put("Soulsilve2010", "");
		users.put("Sonic Angel Knight", "");
		users.put("Stovven", "");
		users.put("easycrashing", "");
		users.put("marcoz9999", "");
		users.put("T3CHNOLOG1C", "");
		users.put("VinsCool", "");
		users.put("Keyblade Spirit", "");
		users.put("Drakia", "");
		users.put("xXPaulMCXx", "");
		users.put("Quantumcat", "quntumcat");
		users.put("punderino", "");
		users.put("DarkSynopsis", "");
		users.put("LuigiXHero", "");
		users.put("enigma85", "");
		users.put("FierceDietyLink1", "");
		users.put("Ghost Liberator", "");
		users.put("flarn2006", "");
		users.put("raphamotta", "");
		users.put("Albireo6972", "");
		users.put("vpd", "");
		users.put("proflayton123", "");
		users.put("Lucca_", "");
		users.put("omar_0215", "");
		users.put("Kitawa", "");
		users.put("Zabhahs", "");
		users.put("Cesar9883", "");
		users.put("Marcsoup", "");
		users.put("caitsith2", "");
		users.put("icefire82G", "");
		users.put("Xppp1", "");
		users.put("eroz76", "");
		users.put("moops44", "");
		users.put("Jared96", "");
		users.put("hab", "");
		users.put("AleAle-20", "");
		users.put("Excalibur007", "");
		users.put("Kuroi-Akira", "");
		users.put("JLsoft", "");
		users.put("daxtsu", "");
		users.put("Lord Toon", "");
		users.put("Xabring", "");
		users.put("Platinum Lucario", "");
		users.put("doughmay", "");
		users.put("Kokumotsu", "");
		users.put("sebamendoza201x", "");
		users.put("hobbledehoy899", "");
		users.put("vt6446", "");
		users.put("cooler9711", "");
		users.put("kend09g", "");
		users.put("WolfRoms", "");
		users.put("AyanamiRei0", "");
		users.put("touholic", "");
		users.put("MrMann", "");
		users.put("ihaveamac", "");
		users.put("kurisumx", "");
		users.put("ishygdaft", "");
		users.put("Jayro", "");
		users.put("BARNWEY", "");
		users.put("loopsbee8", "");
		users.put("Ominous66521", "");
		users.put("maorninja", "");
		users.put("MadMageKefka", "");
		users.put("CamoHiddenDJ", "");
		users.put("ferrao", "");
		users.put("EmuAGR", "");
		users.put("Thorsb", "");
		users.put("Dark Imakuni", "");
		users.put("Amapola62", "");
		users.put("Grim Ripper", "");
		users.put("Cameron Lee", "");
		users.put("Goombi", "");
		users.put("PabloMK7", "");
		users.put("SkillingCat", "");
		users.put("Dimensional", "");
		users.put("Za_Bravens", "");
		users.put("Calsam12", "");
		users.put("lisreal2401", "");
		users.put("Lyncanroc", "");
		users.put("MartyDreamy", "");
		users.put("alex61194", "");
		users.put("Februarysn0w", "");
		users.put("dibmem", "");
		users.put("Yepi69", "");
		users.put("noblues29757", "");
		users.put("tunip3", "");
		users.put("Nim112", "");
		users.put("Plushie", "");
		users.put("BarteringRam", "");
		users.put("ferminuno", "");
		users.put("Daggot", "");
		users.put("ZeraTron", "");
		users.put("Jixun.Moe", "");
		users.put("Rasa39", "");
		users.put("Yersson9876", "");
		users.put("LennyMcLennington", "");
		users.put("TheFlamingFurret", "");
		users.put("Creeperiano99", "");
		users.put("Angelcraft", "");
		users.put("izumo", "");
		users.put("Lycanroc", "");
		users.put("fenixcumber", "");
		users.put("jivansky", "");
		users.put("dimmidice", "");
		users.put("SoulCoder", "");
		users.put("Doumekxkai", "");
		users.put("Pender666", "");
		users.put("TheGrayShow1467", "");
		users.put("Invision", "");
		users.put("ArceusMI", "");
		users.put("Adrot", "");
		users.put("M_1", "");
		users.put("Gattino", "");
		users.put("GhostLatte", "");
		users.put("Demonshen", "");
		users.put("Steinyamite", "");
		users.put("Kaisogen", "");
		users.put("Yoshi9288", "");
		users.put("Flaflo", "");
		users.put("SoulEater98", "");
		users.put("CitizenSnips", "");
		users.put("Xandrid", "");
		users.put("jamezfat", "");
		users.put("PureAznPro", "");
		users.put("kikongokiller", "");
		users.put("Dann_", "");
		users.put("CaptainSwag101", "");
		users.put("Hardt", "");
		users.put("Larsenv", "");
		users.put("Sev501", "");
		users.put("clank714", "");
		users.put("ItsTheScallywag", "");
		users.put("Sheimi", "");
		users.put("noX1609", "");
		users.put("bekzboo12", "");
		users.put("m1geulpf", "");
		users.put("Carlos_DobleC", "");
		users.put("NichyXD", "");
		users.put("TLNiles", "");
		users.put("Inochi.noZenmai", "");
		users.put("epickid37", "");
		users.put("OutVolt", "");
		users.put("ArugulaZ", "");
		users.put("annson24", "");
		users.put("Dennis G", "");
		users.put("jt_1258", "");
		users.put("Ridge", "");
		users.put("rn_1604", "");
		users.put("MashedPotatos", "");
		users.put("CoolFangs", "");
		users.put("Jasper Jackson", "");
		users.put("nechigawara", "");
		users.put("grubgrub", "");
		users.put("elmis003", "");
		users.put("Oleboy555", "");
		users.put("w0nd3rb0yfx", "");
		users.put("Roxie Mika", "");
		users.put("Ecko3351", "");
		users.put("sleepymanakete", "");
		users.put("DaBlackDeath", "");
		users.put("OsQ_Oscar", "");
		users.put("bennyman123abc", "");
		users.put("dude22072", "");
		users.put("Falkiner", "");
		users.put("Nekukun97", "");
		users.put("karloz25", "");
		users.put("Dark Pulse", "");
		users.put("Emenaria", "");
		users.put("GraFfiX420", "");
		users.put("TheLegendofMario", "");
		users.put("MFed", "");
		users.put("Soda_j", "");
		users.put("rsc-pl", "");
		users.put("Carlos Almuna", "");
		users.put("driverdis", "");
		users.put("Xyrenia", "");
		users.put("TwistedZeon", "");
		users.put("Byokugen", "");
		users.put("ntr-", "");
		users.put("Benja81", "");
		users.put("RHOPKINS13", "");
		users.put("AshleyCummings", "");
		users.put("RazorStrike", "");
		users.put("Pepy550", "");
		users.put("Jdbye", "");
		users.put("Lush", "");
		users.put("lone_wolf323", "");
		users.put("Plailect", "");
		users.put("RypaFire", "");
		users.put("Lucar", "");
		users.put("Joey23475", "");
		users.put("einhuman197", "");
		users.put("maorninja", "");
		users.put("DuoForce", "");
		users.put("coolfuze", "");
		users.put("jmhannz", "");
		users.put("Hyoretsu", "");
		users.put("Drew That Gamer", "");
		users.put("Blaze Uchiha", "");
		users.put("Kubas_inko", "");
		users.put("godreborn", "");
		//users.put("");
	}

	public boolean isVerified (String user)
	{
		String thing = users.get(user);
		if(thing != null) return true;
		return false;
	}

	public int getSize()
	{
		return users.size();
	}

	public String getGravatar(String user)
	{
		String thing = users.get(user);
		if(thing == null) return null; //should be verified before we get here, but just in case?
		if(thing.equals("")) return user;
		return thing;
	}

}
